(T.url||(T.url={})).getQueryValue=function(a,b){var b=b||location.href,c=RegExp("(^|&|\\?|#)"+baidu.string(a).escapeReg()+"=([^&#]*)(&|$|#)","");return(c=b.match(c))?c[2]:""};T.url.escapeSymbol=function(a){return String(a).replace(/[#%&+=\/\\\ \　\f\r\n\t]/g,function(b){return"%"+(256+b.charCodeAt()).toString(16).substring(1).toUpperCase()})};
T.url.jsonToQuery=function(a,b){var c=[],d,e=b||function(b){return T.url.escapeSymbol(b)};T.object.each(a,function(b,a){if(T.lang.isArray(b)){d=b.length;for(var i=0;i<d;i++)c.push(a+"="+e(b[i],a))}else c.push(a+"="+e(b,a))});return c.join("&")};T.url.queryToJson=function(a){for(var a=a||location.href,a=a.substr(a.lastIndexOf("?")+1).split("&"),b=a.length,c={},d,e,f,g=0;g<b;g++)a[g]&&(e=a[g].split("="),d=e[0],e=e[1],f=c[d],"undefined"==typeof f?c[d]=e:T.lang.isArray(f)?f.push(e):c[d]=[f,e]);return c};
try{document.execCommand("BackgroundImageCache",!1,!0)}catch(e$$5){}if(window.Raphael){var attrs=Raphael._availableAttrs;attrs.font='12px "Arial", "Microsoft Yahei"';attrs["font-size"]="12";if(!Raphael.svg)attrs.font='12px "Microsoft Yahei"',attrs["font-size"]="12"}var BID=BaiduIndex=BID||{};(function(a){var a=a||window,b=["#6e87d7","#11c897","#fa7256","#b172c5","#f367a7"],c=b.length,d=function(a){return b[(a||0)%c]};d.colors=b;a.getColor=d;var e={noData:"暂无相关数据",noDataP:'<p class="nodata">暂无相关数据</p>',noDataSpan:'<span title="暂无数据" style="font-family:simsun;">－</span>',noDataAttr:{fill:"#666666"},noType2:"当前页无法按地域对比",noCmsg:"您还没有填写反馈意见",tooCmsg:"很抱歉，我们限制了字数为 1000 以内，超长部分将被丢弃。",lVerify:"验证码不正确",xVerify:"验证码输入错误，请重新输入",xVerify5:"验证码错误次数太多，请稍后再试",tVerify:"请输入验证码",nVerify:"请输入验证码",hptp_myIndus:"本报告助您分析：<br />供您查看行业权限状态。",
hptp_myAdds:"本报告助您分析：<br />可以将百度指数未收录的关键词加入百度指数。请注意：<br />            1、创建新词后，从第二天起指数为该词提供1年的数据计算服务，并且该词相关数据将向所有用户公开。服务到期后，若该词未被指数或其他用户收录，需重新创建；<br />            2、关键词一经添加，即被视为消费完毕，无法删除或更改；<br />            3、服务状态包括“正常”和“已过期”，创建新词后的1年内都属于正常服务期，1年后服务过期；<br />            4、关键词状态包括“已收录”和“未收录”。“已收录”代表关键词已被指数机器人自动收录或用户人工收录，“未收录”则代表机器人和用户均未创建该词。",hptp_myAtts:"本报告助您分析：<br />将经常查看的关键词放入“我收藏的指数”，供您随时查看趋势。最多可以收藏50个关键词。",hptp_hours:"本报告助您分析：<br />提供在自定义时间段内，行业搜索时间分布特征。助您按时段精细化投放广告。若在13:00~14:00间，行业搜索指数A为最高，那么我们会将该时段的指数视为100；其他时间段的指数按比例折算，比如9:00~10:00量为B，则其指数=100*(B/A)。",
hptp_IndSub:"本报告助您分析：<br />提供细分行业搜索份额排行，助您了解行业需求格局。",hptp_IndCrowd:"本报告助您分析：<br />提供在自定义时间段内，行业人群性别、年龄、兴趣分布数据。助您精确定位潜在人群。",hptp_IndTrend:"本报告助您分析：<br />提供行业搜索热度数据，可按搜索来源分开查看整体/桌面端/移动端趋势。行业指数与关键词搜索指数计算方法不同，图中行业指数的数字表示相对于图表中的峰值的搜索热度。如果在指定时间范围内，10月1日量A最高，那么我们会将10月1日的指数视为 100；其他时间指数按比例折算，比如9月30日量为B，则其指数=100*(B/A)。",hptp_cMap:"本报告助您分析：<br />提供关键词访问人群在各省市的分布。助您了解关键词的地域分布，特定地域用户偏好可进行针对性的运营和推广。",hptp_RS:"本报告助您分析：<br />提供关键词最热门相关检索词，以及上升最快的相关检索词。助您及时掌握网民搜索习惯，挖掘热门关键词。",hptp_IndRS:"本报告助您分析：<br />提供在自定义时间段，行业内用户关注度最高的TOP搜索词，以及用户关注度上升最快的TOP搜索词。助您及时获取行业热词。",
hptp_demand:"本报告助您分析：<br />提供关键词搜索需求分布信息，助您了解网民对信息的聚焦点，对产品服务的痛点。",hptp_bbs:"本报告助您分析：<br />提供百度收录的最新的TOP10论坛帖子，论坛数据按日更新，不支持自定义时间段筛选。采用论坛帖子标题包含关键词的统计标准。提供原文跳转。",hptp_news:"本报告助您分析：<br />根据自定义时间段，查询关键词媒体指数，同时可查看该时段内的TOP10热门新闻。采用新闻标题包含关键词的统计标准，提供新闻原文地址跳转。",hptp_weibo:"本报告助您分析：<br />根据自定义时间段，查询关键词相关热门微博。采用微博正文包含关键词的统计标准，提供微博原文地址跳转。",hptp_zhidao:"本报告助您分析：<br />根据自定义时间段，查询关键词相关百度知道热门问题。采用问题标题包含关键词的统计标准，百度知道问题的热门程度由问题浏览量决定。提供百度知道问题原文地址跳转。",hptp_interest:"本报告助您分析：<br />提供关键词访问人群的兴趣分布情况，每个关键词展现人群最关注的四个兴趣点。比如关键词“美股”在图表上对应四边形覆盖的兴趣分别为“影视Fans”、“理财精英”、“家庭医生”、“网络小说迷”，这代表关注“美股”的网民平时对影视节目、理财知识、健康护理、网络文学等关注程度最高。图表中，兴趣人群连线距离越小，差异度越小，反之越大。",
hptp_social:"本报告助您分析：<br />提供关键词访问人群的性别、年龄分布情况。",hptp_tProfile:"本报告助您分析：<br />提供关键词搜索指数在最近7天和最近30天的平均值，以及其同比、环比变化趋势；可按搜索来源分开查看整体/移动端趋势。",hptp_trend:"本报告助您分析：<br />根据自定义时间段和自定义地域，查询关键词搜索指数和媒体指数；搜索指数可按搜索来源分开查看整体/移动端趋势，媒体指数不做来源区分。",hptp_myorders:"本报告助您分析：<br />我的购买记录：可以查看创建新词服务购买情况。请您在创建新词权限有效期内新增关键词，过期无效。",tpl_addFav:"您已收藏[0]个关键词，还能收藏[1]个关键词，当前收藏请求超过[2]个，请缩减收藏词量。",tpl_addWord:"您已添加[0]个关键词，还能添加[1]个关键词，当前添加请求超过[2]个，请缩减添加词量。",_end_:""};a.sTips=e;a.stpl_sTips=function(b,a){for(var c=e[b],h=a.length;h--;)c=
c.replace(RegExp("\\["+h+"\\]","gi"),a[h]);return c};var f=function(){T("#sTipbox").fadeOut()};a.showTip=function(b){if(e[b]){var c=a.getEvt(),d=c.target,h=c.pageX,c=c.pageY,l=T("#sTipbox");l.length||(l=T('<div id="sTipbox"></div>').appendTo(document.body));l.data("tipKey")!=b&&l.data("tipKey",b).html(e[b]);if(!d.onmouseout)d.onmouseout=f;l.css({left:h+20,top:c-45}).stop(!0,!0).show()}}})(BID);(function(a){var a=a||window,b,c=function(){if(b)return c;b=c.datas={};for(var a=-1,d;d=strArr[++a];){d=d.split(",");var e="c"+d[0],j=1,h=0,l="",k={};for(b[e]={pid:"c0",name:d[1],subs:k};h=d[++j];)h="c"+h,l=d[++j],k[h]=l,b[h]={pid:e,name:l}}return c};c.citys=function(a,c){String(a).charAt(0)!="c"&&(a="c"+a);var d=b[a]||{};if(d.pid!=="c0")return"";if(!c)return d.name;var d=d.subs,j;for(j in d)if(a=j.slice(1),c(a,d[j]))break};var d=c.city=function(a){String(a).charAt(0)!="c"&&(a="c"+a);a=b[a];return!a||
a.pid==="c0"?{}:{name:a.name,pid:a.pid.slice(1)}},e=c.getName=function(a){String(a).charAt(0)!="c"&&(a="c"+a);return(b[a]||{}).name||""};c.get_name=function(b,c,i){if(b=="0")return"全国";var j=d(b);return!j.pid?e(b):e(j.pid)+(c||" - ")+a.subStr(j.name,i||10)};strArr=c.strArr=["911,北京,514,北京","910,上海,57,上海","913,广东,95,广州,94,深圳,196,佛山,199,惠州,212,汕头,133,东莞,203,茂名,198,江门,200,珠海,197,湛江,209,肇庆,205,揭阳,207,中山,201,韶关,202,阳江,195,云浮,211,梅州,208,清远,204,潮州,213,汕尾,210,河源","923,天津,164,天津","927,河南,168,郑州,378,洛阳,262,南阳,263,新乡,373,信阳,370,安阳,266,平顶山,371,驻马店,265,焦作,381,三门峡,375,周口,268,许昌,264,开封,376,商丘,380,濮阳,379,漯河,374,鹤壁",
"914,四川,97,成都,98,绵阳,107,乐山,106,德阳,103,泸州,113,达州,291,眉山,111,自贡,104,南充,102,内江,96,宜宾,108,广安,114,雅安,109,资阳,99,广元,100,遂宁,112,攀枝花,101,巴中,417,甘孜,479,凉山,457,阿坝","904,重庆,11,重庆","916,江苏,126,苏州,125,南京,127,无锡,161,徐州,169,镇江,160,盐城,163,南通,162,常州,158,扬州,159,泰州,156,连云港,172,宿迁,157,淮安","906,湖北,28,武汉,35,宜昌,31,荆州,32,襄樊,36,十堰,34,荆门,33,黄冈,41,孝感,30,黄石,40,咸宁,38,恩施,37,随州,39,鄂州,42,仙桃,74,潜江,73,天门","917,浙江,138,杭州,149,温州,289,宁波,135,金华,287,台州,304,嘉兴,303,绍兴,305,湖州,134,丽水,288,衢州,306,舟山","909,福建,50,福州,55,泉州,54,厦门,56,漳州,87,宁德,52,三明,51,莆田,253,南平,53,龙岩",
"921,黑龙江,152,哈尔滨,153,大庆,324,绥化,319,齐齐哈尔,320,佳木斯,322,牡丹江,300,黑河,323,鸡西,295,伊春,301,鹤岗,359,双鸭山,302,七台河,297,大兴安岭","901,山东,1,济南,77,青岛,80,潍坊,78,烟台,79,临沂,81,淄博,353,泰安,352,济宁,83,聊城,82,东营,88,威海,86,德州,76,滨州,356,莱芜,85,枣庄,84,菏泽,366,日照","924,陕西,165,西安,275,渭南,277,咸阳,273,宝鸡,276,汉中,278,榆林,272,安康,401,延安,274,商洛,271,铜川","920,河北,141,石家庄,261,唐山,259,保定,148,沧州,292,邯郸,143,衡水,146,秦皇岛,147,廊坊,293,邢台,145,承德,144,张家口","907,辽宁,150,沈阳,29,大连,217,锦州,215,鞍山,224,辽阳,219,丹东,221,营口,220,本溪,218,铁岭,222,抚顺,216,朝阳,223,阜新,225,葫芦岛,151,盘锦","922,吉林,154,长春,270,吉林,525,延边,155,四平,410,白城,407,通化,194,松原,408,白山,191,辽源",
"915,云南,117,昆明,337,红河,123,玉溪,339,曲靖,334,大理,437,文山,438,保山,342,丽江,335,昭通,662,思茅,350,临沧,124,楚雄","926,新疆,467,乌鲁木齐,280,石河子,563,塔城,317,克拉玛依,315,阿克苏,312,哈密,499,巴音郭楞,383,阿勒泰,311,昌吉,660,伊犁哈萨克,310,吐鲁番,384,喀什,318,博尔塔拉,653,克孜勒苏柯尔克孜,386,和田,661,五家渠","912,广西,90,南宁,89,柳州,91,桂林,131,百色,119,河池,132,梧州,93,贵港,118,玉林,128,北海,129,钦州,506,来宾,92,贺州,130,防城港","929,山西,231,太原,233,运城,237,吕梁,230,晋中,232,临汾,227,大同,234,晋城,228,长治,229,忻州,236,阳泉,235,朔州","908,湖南,43,长沙,46,株洲,45,衡阳,49,郴州,68,常德,44,岳阳,269,永州,405,邵阳,67,怀化,48,益阳,47,湘潭,66,娄底,226,张家界,65,湘西",
"903,江西,5,南昌,10,赣州,6,九江,9,上饶,137,景德镇,115,吉安,7,鹰潭,256,宜春,8,抚州,136,萍乡,246,新余","928,安徽,189,合肥,182,滁州,179,宿州,186,安庆,181,六安,187,蚌埠,391,亳州,184,阜阳,188,芜湖,176,宣城,177,巢湖,173,铜陵,178,淮南,185,马鞍山,183,淮北,174,黄山,175,池州","905,内蒙古,20,呼和浩特,25,呼伦贝尔,21,赤峰,13,包头,15,巴彦淖尔,22,通辽,14,鄂尔多斯,16,乌海,331,乌兰察布,333,兴安盟,19,锡林郭勒盟,17,阿拉善盟","925,甘肃,166,兰州,283,武威,285,张掖,286,嘉峪关,308,天水,307,平凉,344,陇南,281,庆阳,282,定西,284,酒泉,309,白银,343,金昌,346,临夏","930,海南,239,海口,243,三亚,244,儋州,241,万宁,582,五指山,242,琼海,456,东方","902,贵州,2,贵阳,59,遵义,4,六盘水,3,黔南,426,毕节,424,安顺,422,铜仁,61,黔东南,588,黔西南",
"919,宁夏,140,银川,395,吴忠,472,石嘴山,396,固原,480,中卫","918,青海,139,西宁,608,海西,659,玉树,652,海东","931,台湾","932,西藏,466,拉萨,655,那曲,656,林芝,516,日喀则","933,香港,663,香港","934,澳门,664,澳门"];return a.cityIDname=c})(BID);(function(a){a=a||window;a.each=function(b,a){var d={}.toString.call(b);if(d.indexOf("Array")>0)for(var d=0,e=b.length;d<e;d++){if(a.call(b,d,b[d]))break}else if(d.indexOf("Object")>0||d.indexOf("Function")>0)for(e in b)if(a.call(b,e,b[e]))break};a.sCopy=function(b,a){for(var d in a)d in b||(b[d]=a[d]);return b};a.nCopy=function(b,c){var d=a.sCopy({},b);return a.sCopy(d,c)};a.gsid=function(a){var c=0;a+="_gsid_";return function(d){var e=d?d.id||"":"";if(e==="")e=a+c++,d&&(d.id=e);return e}}("auto");
a.getEvt=function(b){for(var c=32,d=window.event,e=arguments.callee;!d&&c--&&(e=e.caller);)d=e.arguments[0],(""+d).indexOf("Event]")<1&&(d=0);if(d){d=T.event(d);if(b)d.target=a.tcFilt(d.target,b);return d}};a.tcFilt=function(a,c){var d=c.split(".");d[0]&&a.tagName&&d[0]!==a.tagName.toLowerCase()&&(a=null);if(d[1]&&a&&(a.className||"").indexOf(d[1])<0)a=null;return a};a.getPnode=function(b,c,d,e){var d=d||-1,f=b;do if(b=a.tcFilt(f,c))return b;else d--?e&&e==f&&(f={}):f={};while(f=f.parentNode);return f};
a.getAh=function(a,c){var a=typeof a==="string"?a:a.href,d=a.lastIndexOf("#");c&&T.event(c).preventDefault();return d<0?"":a.slice(d+1)};a.byteLength=function(a){return a.replace(/[^\x00-\xff]/g,"UU").length};a.subStr=function(b,c){c=c||16;if(a.byteLength(b)<=c)return b;c-=2;for(var d=c/2|0,e=b.slice(0,d),f=a.byteLength(e),e=[e];f<c;)e.push(b.charAt(d)),f++,b.charCodeAt(d++)>255&&f++;f>c&&e.pop();return e.join("")+"…"};a.Commafy=function(b,c){return isNaN(b)?a.sTips.noDataSpan:String(b).replace(/(\d{1,3})(?=(\d{3})+(?:$|\.))/g,
"$1,")+(c||"")};a.Rommafy=function(b,c){var b=Math.round(b),d=""+b;if(b!=b)return a.sTips.noDataSpan;b>1E3?d="大于1000":b<-1E3&&(d="小于-1000");return d+(c||"")};a.Rommafy_img=function(b,c){var d={"%":10,",":12},b=a.Rommafy(b,c);return b=b.replace(/[0-9,%]/g,function(a){return'<i style="background-position:-'+(d[a]||a)*8+'px -2px;"></i>'})};a.rat_0=function(a){a=parseFloat(a);return isNaN(a)?"ratNaN":a==0?"rat__":a>0?"ratUp":"ratDown"};a.hi_lite=function(a,c){a=String(a);if(a.indexOf("+")<=0)return c.replace(RegExp(T.string(a).escapeReg(),
"gi"),"<em>"+a+"</em>");for(var a=a.split("+"),d=a.length;d--;)c=c.replace(RegExp(T.string(a[d]).escapeReg(),"gi"),"<em>"+a[d]+"</em>");return c}})(BID);
(function(a){var b={},c=function(a,b,c){c=[].slice.call(arguments,2);return d(a,function(a,d){var h=d.scope||b;if(d.gt)clearTimeout(d.timer),d.timer=setTimeout(function(){d.fun.apply(h,c)},d.gt);else if(d.lt){var e=d.lastTime||-d.lt,k=+new Date;clearTimeout(d.timer);k-e>=d.lt?(d.fun.apply(h,c),d.lastTime=k):d.timer=setTimeout(function(){d.fun.apply(h,c)},d.lt)}else d.fun.apply(h,c)})},d=c.each=function(a,d){for(var g=b[a]||(b[a]=[]),i=-1,j=0;j=g[++i];)if(d(i,j))break;return c};c.abort=function(a){return d(a,
function(a,b){clearTimeout(b.timer)})};c.care=function(a,f,g){g=g||{};g.fun=f;var i=-1;d(a,function(a,b){if(b.fun===f)return i=a,1});if(i<0)i=b[a].length;b[a][i]=g;return c};c.ease=function(a,f){var g=-1;d(a,function(a,b){if(b.fun===f)return g=a,1});g>=0&&b[a].splice(g,1);return c};return(a||window).evts=c})(BID);
(function(a){var b=0,c=function(a){a=a?g(a):d();a!==a&&(a=d());return new i(a)};c.adjust=function(a){return b=a*1E3-new Date};var d=c.cNow=function(){return+new Date+b},e=c.monthHead=function(a){a=new Date(a);return+new Date(a.getFullYear()+"/"+("0"+(a.getMonth()+1)).slice(-2)+"/01")},f=c.monthEnd=function(a){a=new Date(e(a));a=new Date(a.setMonth(a.getMonth()+1));return+new Date(a.setDate(a.getDate()-1))},g=c.parse=function(a){if(typeof a==="number")return new Date(a);else if({}.toString.call(a).slice(-6)===
" Date]")return a;a=String(a);if(/^\d*$/.test(a))switch(a.length){case 4:case 6:case 8:a+="0101".slice(0,8-a.length);a=a.slice(0,4)+"/"+a.slice(4,6)+"/"+a.slice(-2);break;default:a=""}else a=a.replace(/[年月-]/g,"/").replace("日"," "),a=a.replace(/[时分]/,":").replace("秒",""),a=a.replace(/\s+/," ").replace(/^ | $/,"").replace(/ ?\/ ?/,"/"),a.indexOf(" ")<0&&(a=a.split("/"),a[1]=a[1]||"01",a[2]=a[2]||"01",a=a.join("/"));return new Date(a)},i=c.init=function(a){this.stamp=+a;this.Date=new Date(this.stamp)},
j=i.prototype;j.setval=function(a){this.stamp=a;return this};j.settpl=function(a){this.tpl=a;return this};j.valueOf=function(){return this.stamp};j.toString=function(){return this.format("yyyy-mm-dd")};j.format=function(a){var a=a||this.tpl||"yyyymmdd",b=new Date(this.stamp),c=""+b.getFullYear(),d=("0"+(b.getMonth()+1)).slice(-2),j=("0"+b.getDate()).slice(-2),f=("0"+b.getHours()).slice(-2),e=("0"+b.getMinutes()).slice(-2),b=("0"+b.getSeconds()).slice(-2),a=a.replace("yyyy",c).replace("yy",c.slice(-2)),
a=a.replace("mm",d).replace("dd",j);return a.replace("hh",f).replace("nn",e).replace("ss",b)};j.monthHead=function(){this.stamp=e(this.stamp);return this};j.monthEnd=function(){this.stamp=f(this.stamp);return this};j.diff=function(a,b){var c=new Date(this.stamp);if(typeof b!=="number")return c["get"+a]();this.stamp=c["set"+a](c["get"+a]()+b);return this};j.year=function(a){return this.diff("FullYear",a)};j.month=function(a){return this.diff("Month",a)};j.date=function(a){return this.diff("Date",a)};
j.difs=function(a,b){a=a?g(a):d();return(this.stamp-a)/1E3/({s:1,n:60,h:3600,d:86400}[b]||1)};j.smart=function(a){var a=this.difs(a,"n"),b=a>0?"后":"前",c="数秒",a=Math.abs(a);if(a>525600)return this.format("yyyy年mm月");else a>43200?c=parseInt(a/43200)+" 个月":a>1440?c=parseInt(a/1440)+" 天":a>60?c=parseInt(a/60)+" 小时":a>1&&(c=parseInt(a)+" 分钟");return c+b};j.months=function(a){a=a?g(a):d();a=a.getFullYear()*12+a.getMonth();a=this.Date.getFullYear()*12+this.Date.getMonth()-a;return a+(a<0?-1:1)};return(a||
window).fnsDate=c})(BID);
(function(a,b){var c={},d={},e=[],f=function(a,b,f){var e=d[a];if(e)return g(a),b(e);var m=c[a]||(c[a]=[]);m.push(b)>1||(f=f||{},T.ajax(a,{async:f.async===!1?!1:!0,timeout:f.timeout||15E3,error:f.error,success:function(b){i(a,b);for(var d=0;d<m.length;d++)m[d](b);delete c[a]}}))},g=function(a){for(var b=e.length;b--;)if(e[b]===a){e.splice(b,1);e.push(a);break}},i=f.setCach=function(a,b){if(d[a])d[a]=b,g(a);else{if(e.length>=50){var c=e.shift();delete d[c]}e.push(a);d[a]=b}};(a||window)[b||"cjax"]=
f})(BID);
(function(a){var b,c,d,e;(a.nearStep=function(a,j,h){f(a,j,h);if(e==0)if(c==0)return[0,d,1];else e=(c<0?-1:1)*c/d,c+=e/2,b-=e/2;return g()}).intg=function(a,e,h){f(a,e,h);return c-b<d?(a=(d-(c-b))/2,c=Math.round(c+a),b=Math.round(b-a),b<0&&(c-=b,b=0),[b,c,1]):g()};var f=function(a,f,h){d=h||5;b=a||0;c=f||0;b>c&&(c=b);e=c-b},g=function(){for(var a=Math.floor(Math.log(e)/Math.LN10),f=Math.pow(10,a-1),h=f*Math.ceil(e/f/d),g=Math.floor(b/f)*f,k=g+h*d;k<c;)h+=f,k=g+h*d;f=0;if(String(h).indexOf(".")>=0)f=
Math.abs(a)+4,h=+h.toFixed(f),f=String(h).split(".").pop().length,g=+g.toFixed(f),k=+k.toFixed(f);return[g,k,h,f]}})(BID);(function(a){var b=a.MNKO={};b.MM=function(a){return[Math.min.apply(0,a),Math.max.apply(0,a)]};b.MN=function(a){for(var b=2E9,e=-b,f=a.length,g=f;f--;)g=a[f],g<b&&(b=g),g>e&&(e=g);return[b,e]};b.MK=function(a,d){for(var d=d||b.MM(a),e=d[0],f=d[1]-e,g=[],i=a.length;i--;)g[i]=(a[i]-e)/f;return g};b.MO=function(a,d){for(var d=d||b.MM(a),e=d[1],f=[],g=a.length;g--;)f[g]=a[g]/e;return f}})(BID);(function(a){a=a||window;return a.tabFun=function(){var b=a.getEvt(),c=a.getPnode(b.target,".tabLi");if(c&&!T(c).hasClass("curr")&&!T(c).hasClass("dsab")){var d=-1,b=a.getPnode(c,".tabUl"),e=a.getPnode(b,".tabUnit");T(b).children(".tabLi").removeClass("curr").each(function(a){if(this===c)return d=a,T(this).addClass("curr"),"break"});T(e).children(".tabConts").children(".tabCont").addClass("dsn").eq(d).removeClass("dsn");b.id&&a.evts(b.id+"_tabClick",b,d)}}})(BID);
(function(a){var a=a||window,b=function(){T("#"+this.getAttribute("hold_label")).hide()},c=function(){this.value==""&&T("#"+this.getAttribute("hold_label")).show()};return a.placehold=function(d,e){e=e||{};return T(d||"input.hold_efkt").each(function(){var d=T(this),g=d.attr("hold_txt"),i=T("#"+d.attr("hold_label")),j=a.gsid(this);if(e.text)g=e.text;if(g){if(!i.length){i=T('<label class="hold_label" for="'+j+'"></label>');d.attr("hold_label",a.gsid(i[0]));if(e.cssText)i[0].style.cssText=e.cssText;
d.before(i);d.on("focus",b).on("blur",c)}d.val()&&i.hide();g=g.replace(/\\n/g,"<br />");i.html(g)}else i.remove(),d.off("focus",b).off("blur",c)})}})(BID);
BID.schnav_click=function(){var a=BID.getEvt().target,b=a.getAttribute("name"),c={news:"ns?tn=news&cl=2&rn=20&ct=1&ie=utf-8&word=",baidu:"s?fr=index&wd=",tieba:"f?ie=utf-8&kw=",zhidao:"search?pn=0&rn=10&lm=0&word=",music:"search/tag/",image:"i?ct=201326592&cl=2&nc=1&lm=-1&st=-1&tn=baiduimage&istype=2&fm=&pv=&z=0&ie=utf-8&word=",wenku:"search?ie=utf-8&lm=0&od=0&word=",baike:"search/word?pic=1&sug=1&enc=utf8&word=","":""};if(a.tagName=="A"&&c[b]){var d=T("#schword").val().replace(/^\s+|\s+$/,""),e=
a.href.split("/");e.length=3;e=e.join("/")+"/";d&&(e+=c[b]+encodeURIComponent(d));a.href=e}};
BID.rTools_pos=function(a){var b=0,c=0,d=0,e=0;BID.evts.care("width_resize_all",function(b){d=Math.max(0,(b-1300)/2);b<1E3&&(d=b-1E3);T("#"+a).css({right:d})}).care("height_resize",function(d){b=d;T("#"+a).css({top:b/2-50})}).care("window_scroll",function(f,g){var i=T("#"+a);g>90&&c<=90?i.find(".toTop")[0].style.display="block":g<90&&c>=90&&i.find(".toTop").hide();c=g;T.browser.ie==6&&i.css({top:c+b/2});f!=e&&(e=f,i.css({right:d+Math.max(0,f)}))})("width_resize_all",window,T(window).width())("height_resize",
window,T(window).height())};BID.lTool_fix=function(a,b){var c=a>0?-a:"",d=0,e=T("#lTools_c"),f=e[0].scrollHeight;T("#mainWrap").height();d=BID.w_size;f-=d.height;var g=e.data("lastTop")||0;b<130?d=-Math.max(0,b):f<=0?d=-130:(d=g-d.dirTop,d=d<-f-130?-f-130:d<-130?d:-130);e.css({top:d,left:c});e.data("lastTop",d)};BID.lTool_fix_height=function(a){var b=T("#lTools_c"),c=b[0].scrollHeight,d=T("#mainWrap").height();T("#footer");d+130<a?(c=a-130,b[0].style.height=c+"px"):b[0].style.height="";return c};
T.browser.ie!=6&&T("#lTools_c").length&&(BID.evts.care("window_scroll",BID.lTool_fix),BID.evts.care("height_resize",BID.lTool_fix_height,{lt:100}),BID.evts.care("window_resize",function(){BID.lTool_fix(T(document).scrollLeft(),T(document).scrollTop())},{gt:100}));
BID.lToolslide=function(){T("#lTools");var a=T("#lTools_c"),b=parseInt(a.css("left")),c=-190;b<0&&(c=0);a.stop(!0).animate({left:c},function(){var a=T("#mainWrap"),c=240;b>=0&&(c=50);a.css({"padding-left":c});BID.evts("width_resize")});a=null};
BID.newSuggestion=function(a,b){typeof a!=="string"&&(a=BID.gsid(a));b=baidu.object.extend(b||{},{getData:function(a){var b=this,e=T.string(a).trim();if(e)window.baidu.sug=function(f){if(!f.s||!f.s.length)f.s=[];for(var g=[],i=0;i<f.s.length;i++){var j=f.s[i],h=BID.subStr(j,64).replace(e,'<span style="color:#c00;">'+e+"</span>"),h='<span title="'+j+'">'+h+"<span>";g.push({value:j,content:h})}b.receiveData(a,g)},T("#indexSugSc").remove(),T(document.createElement("script")).attr("id","indexSugSc").attr("src",
"http://nssug.baidu.com/su?prod=index&wd="+encodeURIComponent(e)+"&"+(new Date/864E5|0)).appendTo(document.body)}});return magic.setup.suggestion(a,b)};BID.createScroll=function(a){var b=BID.createScroll,c=b.inis||(b.inis={}),d=BID.gsid(a);a.onmouseover=null;T(a).mouseenter(b.fnHover).mouseleave(b.fnHover);return c[d]=magic.setup.scrollPanel(d,{autoUpdateDelay:!1})};BID.createScroll.fnHover=function(a){T(this)[a.type==="mouseenter"?"removeClass":"addClass"]("hide_slider");T(this).find("a.tang-knob").css({left:0})};
BID.popLogin=function(){var a=BID.popLogin.passv3,b=PPval.hostUrl+PPval.staticUrl+"v3Jump.htm";if(!a)a=BID.popLogin.passv3=passport.pop.init({apiOpt:{product:"index",loginType:1,safeFlag:0,sms:0,u:location.href,staticPage:b},cache:!1,tangram:!0,registerLink:T("#pas_regLink").attr("href"),onLoginSuccess:function(){},onSubmitStart:function(){},onSubmitedErr:function(){},onSystemErr:function(){},onShow:function(){var a=T("#passport-login-pop").find("ul.tab"),b=T('<li class="tab-item"><a onclick="return false;" hidefocus="true">推广帐号</a></li>'),
e=a.find("li.tab-item");e.length==2&&T("#passport-login-pop-api")[0]&&(T("#cas_imgValid").click(),T("#cas_fromu").val(location.href),e.click(function(){T("#passport-login-pop-api").show();T("#cas_loginForm").hide()}),b.click(function(){a.find(".tab-item").removeClass("tab-selected");b.addClass("tab-selected");T("#passport-login-pop-api").hide();T("#cas_loginForm").show()}),a.append(b),a.parent().append(T("#cas_loginForm")))},onHide:function(){},onDestroy:function(){}});a.show()};
BID.cas_submit=function(){var a="";T("#cas_loginForm input").each(function(){var b=T(this).attr("chk_typ"),c=this.value,d=T(this).prevAll("label").text();if(b){if(!c)return a="请填写"+d,"break";switch(b){case "name":if(c.length<3)return a=d+"格式错误","break";break;case "pass":if(c.length<6)return a=d+"不符合要求","break";break;case "code":if(this.value=c=c.replace(/^\s+|\s+$/,""),c.length!=4)return a=d+"有误","break"}}});if(!a)return!0;T("#cas_Error").html(a);return!1};
(function(a){var a=a||window,b="",c="",d=0,e=T.browser.ie==6,f=function(){var c=a.getEvt(),f=c.target,e=" "+f.className+" ";d||(T(document.body).click(h),d=1);b=a.gsid(a.getPnode(f,".selectA"));/ (selectA|sltTxt) /.test(e)||T(f).hasClass("selectA")||T(f.parentNode).hasClass("selectA")?g(c):f.tagName=="A"&&i(c)};f.setVal=function(b,c){c||c===""?b.value=c:c=b.value;var d=j(b);c.length>2?(d.opts.last()[0].href="#"+c,c=c.split("|"),d.txt.html(a.fnsDate(c[0]).format("yyyy年mm月")+"-"+a.fnsDate(c[1]).format("yyyy年mm月"))):
d.opts.each(function(){if(c===a.getAh(this))return d.txt.html(T(this).text()),"break"})};var g=f.slide=function(c){var c=j(c.target),d=c.val.val();c.box.hasClass("slided")?b="":(c.opts.each(function(){a.getAh(this)===d?T(this).addClass("curr"):T(this).removeClass("curr")}),e&&c.box.hasClass("width_ie6")&&c.box.css({width:c.box[0].clientWidth}),c.box.addClass("slided"))},i=f.clickA=function(c){var d=c.target,c=a.getAh(d,c);if(!T(d).hasClass("dsab")&&(b="",!T(d).hasClass("curr"))){var f=j(d);f.val.val(c);
f.txt.html(T(d).text());f.val.change()}},j=f.getNodes=function(b){b=T(a.getPnode(b,".selectA"));return{box:b,val:b.find(".sltVal"),txt:b.find(".sltTxt"),opts:b.find(".sltOpt a")}},h=f.slideUp=function(){if(c&&c!==b){var d=T("#"+c);d.removeClass("slided");e&&d.hasClass("width_ie6")&&d.css({width:""});a.evts&&a.evts("selectA_slideUp",null,d[0])}c=b;b=""};return a.selectA=f})(BID);
(function(a){var a=a||window,b=function(){var b=a.getEvt(),e=b.target;e.tagName=="A"&&a.getAh(e).length>2?(b.preventDefault(),c(e)):a.selectA()},c=b.showPanel=function(b){var c=T(a.getPnode(b,".rangeDate")),f=c.find(".sltVal");a.rangePanel(c.offset(),[c.attr("limitB"),c.attr("limitE"),f.val()],function(g){if(g){var i=a.fnsDate,j=g.split("|"),h=i(j[0]),i=i(j[1]);c.find(".sltTxt").html(h.format("yyyy")+"年"+h.format("mm")+"月-"+i.format("yyyy")+"年"+i.format("mm")+"月");b.href="#"+g;f.val(g).change()}})};
return a.rangeDate=b})(BID);
(function(a){var a=a||window,b=a.fnsDate().month(-3),c=a.fnsDate().date(-1),d=function(){var b=a.getEvt().target,c=a.getPnode(b,".ymDateA");if(!T(c).attr("initD")){var d=e(c);f(c,d);g(c,d);T(c).attr("initD","initD")}a.getPnode(b,".selectA")&&a.selectA()},e=d.getLimits=function(a){var a=T(a),b=a.find(".yearA .sltVal").val(),c=a.find(".monthA .sltVal",a).val();return[a.attr("limitB"),a.attr("limitE"),b+("0"+c).slice(-2)]},f=d.limitYear=function(d,f){var f=f||e(d),d=T(d),h=a.fnsDate,g=h(f[0]||b).year(),
k=h(f[1]||c).year(),h=d.find(".yearA .sltOpt a");if(!h.length){for(var h="",m=g;m<=k;m++)h+='<a href="#'+m+'">'+m+"年</a>";h=d.find(".yearA .sltOpt").html(h).find("a")}h.each(function(){var b=a.getAh(this);b<g||b>k?T(this).addClass("dsab"):T(this).removeClass("dsab")})},g=d.limitMonth=function(d,f){var f=f||e(d),d=T(d),h=a.fnsDate,g=h(f[0]||b).monthHead(),k=h(f[1]||c).monthHead(),m=h(f[2]).year(),n=d.find(".monthA .sltOpt a");if(!n.length){for(var n="",o=1;o<=12;o++)o==7&&(n+="</li><li>"),n+='<a href="#'+
("0"+o).slice(-2)+'">'+("0"+o).slice(-2)+"<i>月</i></a>";n=d.find(".monthA .sltOpt").html("<li>"+n+"</li>").find("a")}n.each(function(){var b=h(m+("0"+a.getAh(this)).slice(-2));b<g||b>k?T(this).addClass("dsab"):T(this).removeClass("dsab")})};d.change=function(){var d=a.getEvt().target,f=d.value,h=T(a.getPnode(d,".ymDateA")),d=h.find("input.ymValue");if(f.length<4)d.val(d.val().slice(0,4)+("0"+f).slice(-2));else{var l=a.fnsDate,k=e(h[0]),m=l(k[0]||b),n=l(k[1]||c),f=l=l(f+l(k[2]).format("mm"));g(h[0],
k);l<m&&(f=m);l>n&&(f=n);f!=l&&(k=f.format("mm"),h=a.selectA.getNodes(h.find(".monthA")[0]),h.val.val(k),h.txt.html(k+"月"));d.val(f.format("yyyymm"))}T(d).change()};return a.ymDateA=d})(BID);
(function(a){var a=a||window,b=a.fnsDate().month(-3),c=a.fnsDate().date(-1),d="",e=0,f="",g=0,i=0;PPval&&PPval.dataStm&&(c=a.fnsDate(PPval.dataStm));var j=function(a,b,c){var d=o();h(d,b);l(d,b);T(d).css({left:a.left+1,top:a.top+24}).show();i=g=1;e=c},h=j.setLimit=function(d,f){var e=a.fnsDate,h=e(f[0]||b).format(),j=e(f[1]||c).format();T(d).find(".ymDateA").each(function(){T(this).attr("limitB",h).attr("limitE",j).attr("initD","")})},l=j.setRange=function(d,f){var d=T(d),e=a.fnsDate,h=[b,c];if(f[2]){var j=
(f[2]+"|").split("|");j[0].length>3&&(h[0]=e(j[0]));j[1].length>3&&(h[1]=e(j[1]))}f[0]&&h[0]<e(f[0])&&(h[0]=e(f[0]));f[1]&&h[1]>e(f[1])&&(h[1]=e(f[1]));var e=h[0].format("yyyy"),j=h[0].format("mm"),g=h[1].format("yyyy"),i=h[1].format("mm"),l;l=d.find(".ymValue");l[0].value=h[0].format();l[1].value=h[1].format();l=d.find(".yearA .sltVal");l[0].value=e;l[1].value=g;l=d.find(".yearA .sltTxt");l[0].innerHTML=e+"年";l[1].innerHTML=g+"年";l=d.find(".monthA .sltVal");l[0].value=j;l[1].value=i;l=d.find(".monthA .sltTxt");
l[0].innerHTML=j+"月";l[1].innerHTML=i+"月"},k=j.clickRange=function(){g=1;var b=a.getEvt("input").target;if(b&&(b.value=="取消"||b.value=="确定"))g=0,b.value=="确定"&&m()},m=j.applyRange=function(e){var h=a.fnsDate,j=T("#"+d+" .ymDateA .ymValue"),g=h(T(a.getPnode(j[0],".ymDateA")).attr("limitB")||b),i=h(T(a.getPnode(j[1],".ymDateA")).attr("limitE")||c),l=j[0].value,k=j[1].value;l>k&&(l=k);l=h(l).monthHead();k=h(k).monthEnd();l<g&&(l=g);k>i&&(k=i);f=[j[0].value=l.format(),j[1].value=k.format()].join("|");
e&&e(f)},n=j.hideRange=function(){i&&!g&&(T("#"+d).hide(),i=0,e&&e(f),e=0,f="");g=0},o=j.getPanel=function(){if(d)return T("#"+d)[0];d=a.gsid(b);var b=document.createElement("div");b.id=d;b.className="rangePanel";T(document.body).click(n);T(b).click(k).html('<div class="ptb05"><span>起始：</span><span class="ymDateA" limitB="" limitE="" onclick="BID.ymDateA()">    <input class="ymValue" value="" />    <span class="selectA yearA">        <input class="sltVal" value="" onchange="BID.ymDateA.change()" />        <span class="sltTxt"></span>        <div class="sltOpt"></div>    </span>    <span class="selectA monthA">        <input class="sltVal" value="" onchange="BID.ymDateA.change()" />        <span class="sltTxt"></span>        <ul class="sltOpt"></ul>    </span></span>        </div><div class="ptb05"><span>结束：</span><span class="ymDateA" limitB="" limitE="" onclick="BID.ymDateA()">    <input class="ymValue" value="" />    <span class="selectA yearA">        <input class="sltVal" value="" onchange="BID.ymDateA.change()" />        <span class="sltTxt"></span>        <div class="sltOpt"></div>    </span>    <span class="selectA monthA">        <input class="sltVal" value="" onchange="BID.ymDateA.change()" />        <span class="sltTxt"></span>        <ul class="sltOpt"></ul>    </span></span>        </div><div class="ptb05 pl20">    <input type="button" class="button ml20" value="确定" />    <input type="button" class="button ml20" value="取消" /></div>        ').appendTo(document.body);
return b};return a.rangePanel=j})(BID);
(function(a){var a=a||window,b=function(){var b=a.getEvt().target,e=T(a.getPnode(b,".selectA"));if(e.length){if(!e.hasClass("slided")){b=e.find(".sltOpt");if(e.hasClass("provA"))b.find("a").length||b.html(c());else{var i=T(a.getPnode(e[0],".regionA")).find(".selectA.provA .sltVal").val(),j=e.find(".sltTxt");j.html(j.text().slice(0,5));b.html(d(i))}(e=a.getPnode(e[0],".comBorderL"))&&(T(e).offset().top>T(document).scrollTop()+T(window).height()/2?b.css({"margin-top":-b.height()-53}):b.css({"margin-top":""}))}a.selectA()}};
b.change=function(){var b=a.getEvt().target,b=T(a.getPnode(b,".selectA")),d=T(a.getPnode(b[0],".regionA")),c=d.find(".regionValue"),e=d.find(".selectA.provA .sltVal"),h=d.find(".selectA.cityA .sltVal");b.hasClass("provA")&&(d.find(".selectA.cityA .sltTxt").html("所有城市"),h.val("0"));h.val()!=""&&h.val()!="0"?c.val(h.val()):c.val(e.val());c.change()};var c=b.buildProv=function(){var b='<dl><dt>&nbsp;</dt><dd><a href="#0">所有省份</a></dd></dl>',d=a.cityIDname(),c;for(c in e)b+="<dl><dt>"+c+"：</dt><dd>",
T.array(e[c]).each(function(a,c){b+='<a href="#'+c+'">'+d.citys(c)+"</a> "}),b+="</dd></dl><dl></dl>";return b},d=b.buildCity=function(b){var c='<dl><dt><a href="#0">所有城市</a></dt><dd>';a.cityIDname().citys(b,function(a,b){c+='<a href="#'+a+'">'+b+"</a> "});return c+"</dd></dl><dl></dl>"},e=b.datStor={"A-G":[928,934,911,904,909,913,925,912,902],"H-J":[920,921,927,908,906,930,922,916,903],"L-S":[907,905,919,918,910,914,901,929,924],"T-Z":[923,931,932,933,926,915,917]};b.setVal=function(b,c){c=c||b.value;
b.value=c=c||"0";var d=T(a.getPnode(b,".regionA")),e=d.find(".regionValue"),h=d.find(".selectA.provA .sltVal"),l=d.find(".selectA.provA .sltTxt"),k=d.find(".selectA.cityA .sltVal"),d=d.find(".selectA.cityA .sltTxt"),m=a.cityIDname(),n=cID=c,o=m.citys(n),p=m.city(cID).name;!o&&!p?(n=cID="0",o="所有省份"):p?(n=m.city(cID).pid,o=m.citys(n)):cID="0";h.val(n);l.html(o);cID!=="0"?(e.val(cID),k.val(cID),d.html(p)):(e.val(n),h.change())};return a.regionA=b})(BID);
BID.crAdvPannel=function(){T("#adv_pannel .comCtl").each(function(){var a=T(this).parent().attr("ctlName");T(this).html(T("#advTpls_"+a).html());if(T.browser.ie==6){var b=this;setTimeout(function(){T(b).find(".rangeDate").css({position:"relative"});T(b).find("i.delComp").css({position:"relative"})},5)}})};
BID.add_del_comp=function(){var a=BID.getEvt().target,b=a.className,c=BID.getPnode(a,".tabCont"),d=T(c).find(".compUl"),e=d.find(".compLi");if(b.indexOf("delComp")>=0)T(c).find(".addComp").removeClass("dsn"),T(a).closest(".compLi").addClass("dsn").appendTo(d).find(".comWord").val("");else{a=BID.getPnode(a,".addComp");if(!a)return;e.each(function(b){b>=e.length-1&&T(a).addClass("dsn");if(T(this).hasClass("dsn"))return T(this).removeClass("dsn"),BID.advPannelFilled&&T(this).find(".comWord").mousedown().focus(),
"break"})}e.filter(".dsn").length>=4?d.addClass("hideDel"):d.removeClass("hideDel");d.find(".compLi").each(function(a){T(this).find(".comBorderR").css({"border-color":BID.getColor(a)})})};
BID.createSug=function(){var a=BID.getEvt().target;a.onmousedown=null;T(a).focus(function(){T(this).css({"background-color":"#fff"}).closest(".comCtl").addClass("curr")}).blur(function(){T(this).css({"background-color":""}).closest(".comCtl").removeClass("curr")}).change(function(){T("#addFavBtn").hide().parent().find(".compVsplit").show()}).keydown(function(a){a.keyCode==13&&BID.advSearch()}).closest(".comCtl").addClass("curr");BID.newSuggestion(a,{offset:{width:199,offsetX:-3,offsetY:0}})};
BID.scroll_resize=function(){function a(){var a=T(document).scrollLeft(),c=T(document).scrollTop();b.dirTop=c-(b.top||0);b.left=a;b.top=c;BID.evts("window_scroll",window,a,c)}if(!BID.w_size){var b=BID.w_size={},c,d;b.width=T(window).width();b.height=T(window).height();a();T(window).scroll(a).resize(function(){var a=T(window).width(),f=T(window).height(),g=0,i=0;b.width=a;b.height=f;if(a!=c){g=1;BID.evts("width_resize_all",window,a);if(a<1E3&&c<1E3||a>1300&&c>1300)return c=a;c=a;BID.evts("width_resize",
window,a)}f!=d&&(i=1,d=f,BID.evts("height_resize",window,f));(g||i)&&BID.evts("window_resize",window,a,f)})}};
BID.addFavWords=function(){var a=BID.getEvt(),b=T(BID.getPnode(a.target,"a"));b.hasClass("rTahref")&&(b.hasClass("setFaved")&&(b.removeClass("setFaved").addClass("setFaving"),BID.dataInterface("Attention/del/","",function(a){a.status==0?b.removeClass("setFaving").addClass("setFav").attr({title:"点击加入收藏"}):b.removeClass("setFaving").addClass("setFaved")},{noCache:1})),b.hasClass("setFav")&&(b.removeClass("setFav").addClass("setFaving"),BID.dataInterface("Attention/add/","",function(a){a.status==0?b.removeClass("setFaving").addClass("setFaved").attr({title:"点击取消收藏"}):
(b.removeClass("setFaving").addClass("setFav"),(new magic.Dialog({draggable:!0,titleText:"温馨提示：",content:a.sErr,contentType:"html",width:280,height:165,mask:{enable:!0}})).render())},{noCache:1})))};
BID.holdReg=function(){var a=BID.getEvt(),b=BID.getPnode(a.target,".holdBox"),c=BID.getPnode(a.target,".comBorderL"),d,e;if(!T(c.parentNode).hasClass("dsab"))if(b)T(b).addClass("slided").closest(".comCtl").find(".comBorderR .delComp").addClass("dsn"),b=T(b).siblings(".regionA"),d=b.find(".provA"),a.target=a.srcElement=d[0],setTimeout(function(){d.eq(0).click()},2);else if(b=BID.getPnode(a.target,".regionA"))if(b=T(b),a.target.tagName==="A"){var c=BID.getAh(a.target),f=BID.getPnode(a.target,".selectA");
if(c!="0"&&T(f).hasClass("provA"))e=b.find(".cityA"),a.target=a.srcElement=e[0],setTimeout(function(){e.eq(0).click()},2)}};BID.holdRegChg=function(){var a=BID.getEvt().target;T(a).closest(".comBorderL").find(".holdBox").find(".holdText").html(BID.cityIDname().get_name(a.value,"",12))};BID.evts.care("selectA_slideUp",function(a){a=T(a);if(a.hasClass("provA")||a.hasClass("cityA"))a.closest(".regionA").find(".slided").length||a.closest(".comBorderL").find(".holdBox").removeClass("slided").closest(".comCtl").find(".comBorderR .delComp").removeClass("dsn")});
BID.showHelpTip=function(a){var b=BID.getEvt("i").target,c;if(b){b=T(b);if(b.hasClass("help")){var d=b.closest(".titlBar");c=d.siblings(".tipinfo");c.length||(a=BID.sTips[a]||a,c=T('<div class="tipinfo"></div>').insertAfter(d).hide(),c.html('<div class="tiparro"><i class="icons tipAup"></i><i class="icons close"></i></div><div class="tipcont">'+a+"</div></div>"));T(document).off("click",BID.hideHelpTip).on("click",BID.hideHelpTip)}c.hasClass("showing")?c.removeClass("showing").stop().slideUp():(b=
b.position(),c.addClass("showing").stop().slideDown().find(".tipAup").css("left",b.left))}};BID.hideHelpTip=function(){var a=1,b=1,c=BID.getEvt(),c=T(c.target),d=c.closest(".tipinfo");d.length?c.hasClass("close")?b=0:a=0:(d=T("div.tipinfo"),c.hasClass("help")&&(a=0));a&&(d.removeClass("showing").stop().slideUp(),b&&T(document).off("click",BID.hideHelpTip))};
(function(a){var a=a||window,b=function(a){if(!(this instanceof b))return new b(a);this.elids={box:a};this.oBox=T("#"+a)},c=b.eHTML=function(a){var b=[];T.array(a).each(function(a,c){b.push(T.string(c).encodeHTML())});return b},d=b.sTPL=function(a,b){for(var c=Array(b||5),d=c.length;d--;)c[d]=a.replace("{index}",d);return c.join("")},e=b.prototype;e.getEl=function(b){var b=b||"box",c=this.elids,d=T("#"+c[b]);if(!d.length){switch(b){case "titlBar":case "tabUnit":d=this.getEl().children("."+b);break;
case "tabTitle":case "tabConts":case "baiduTpl":d=this.getEl("tabUnit").children("."+b);break;case "tabUl":d=this.getEl("tabTitle").children("."+b)}c[b]=a.gsid(d[0])}return d};e.title=function(e,g){var i=this.getEl("titlBar"),j=i.find(".compInfo"),h=a.getParams(),l=a.getParams.C32(),k=[],k=l.c_32;if(b.revert||g&&g.revert)k=l.c32.slice(),h.type==0?k[0]&&k[0].indexOf("年")>0&&(k[0]=l.c_32[0]):k[1]&&k[1].indexOf("年")>0&&(k[1]=l.c_32[1]);h.type==0?(k=[l.tags[0],k[0],k[1]],l.tags.length!=1&&(k[0]="")):
(k=[k[0],k[1],l.tags[0]],k[2]="");T("#industryName").html()&&(k[0]=T("#industryName").html());j.length||(j=i.append(d('<span class="compInfo"></span>',3)).find(".compInfo"));e=c(e);j.eq(0).html(e[0]||k[0]);j.eq(1).html(e[1]||k[1]);j.eq(2).html(e[2]||k[2]);j.each(function(){var a=this.innerHTML;!a||a==" "?T(this).hide():T(this).show()});return this};e.tabTils=function(b,e){var e=e||0,i=this.getEl("tabTitle"),j=this.getEl("tabUl"),h=j.find(".tabLi"),l=a.getParams.C32();h.length||(h=j.append(d('<a class="tabLi gColor{index}" href="javascript:;"><div class="nmTab"></div><div class="hvTab"></div></a>')).find(".tabLi"));
b=b.length?c(b):l.tags;b.length>1?i.show():i.hide();h.hide().removeClass("curr").each(function(a){if(a>=b.length)return"break";T(this).show().find(".nmTab, .hvTab").html(b[a]);this.title=b[a]}).eq(e).addClass("curr");i=this.getEl("tabConts");j=i.children(".tabCont");j.length||(j=i.append(d('<div class="tabCont gColor{index} dsn" style="zoom:1;"></div>')).children(".tabCont"));j.eq(e).removeClass("dsn");return this};return a.sentimBlock=b})(BID);
(function(a){var a=a||window,b,c=0,d=a.vVerify=function(){b||(b=i());b.isShowing()||(g(),T(b.getElement("content")).find(".mainCont").show().siblings(".checking").hide(),b.show(),b.center())};d.hide=function(){b.hide()};var e=d.checkVerify=function(){if(!c){var a=T(b.getElement("content")).find(".verifyInput").val();a?(T(b.getElement("content")).find(".mainCont").hide().siblings(".checking").show(),PPval.status=-301,c=1,BID.dataInterface("Verify/Check/","code="+a,function(a){c=0;if(a.status==0)location.reload();
else{g();T(b.getElement("content")).find(".mainCont").show().siblings(".checking").hide();var d=BID.sTips.xVerify;a.status==2&&(d=BID.sTips.xVerify5);setTimeout(function(){alert(d)},100)}},{noCache:!0})):alert(BID.sTips.lVerify)}},f=d.getCntHtml=function(){var a=['<div class="mainCont">'];a.push('<p class="tiptext">'+BID.sTips.tVerify+"</p>");a.push('<div class="itemtext">验证码：</div>');a.push('<input class="verifyInput" maxlength="4" onkeydown="BID.vVerify.keyDown()" />');a.push('<img class="verifyImg" src="javascript:;" title="点击刷新验证码" onclick="BID.vVerify.refreshImg()" />');
a.push('</div><div class="checking"></div>');return a.join("")},g=d.refreshImg=function(){T(b.getElement("content")).find(".verifyImg").attr("src",PPval.dataface+"Verify/Get/?res="+PPval.ppt+"&"+ +new Date)};d.keyDown=function(){a.getEvt().keyCode==13&&e()};var i=d.getDialog=function(){b=new magic.Dialog({draggable:!0,content:f(),contentType:"html",width:280,height:165,mask:{enable:!0},buttons:{enable:!0,align:"right",items:[{text:"确定",click:e}]}});b.render();b.hide();T(b.getElement("")).addClass("verifyDialog");
T(b.getElement("body")).height(120);T(b.getElement("footer")).height(43);return b}})(BID);(function(a){var a=a||window,b,c,d={0:0,1:89,2:179,3:359,4:719,10:719,11:0,12:6,13:29,14:0},e={0:"当月",1:"最近3个月",2:"最近6个月",3:"最近12个月",4:"全部时间",10:"全部时间",11:"昨天",12:"最近7天",13:"最近30天",14:"当月"},f=function(a){if(b&&!a)return b;else b={};T("#adv_schfm input").each(function(){var a=this.name,d=this.value,c=d.split(/[,，]+/);a==="type"&&(c=d);b[a]=c});switch(b.type){case "1":b.word.length=b.time.length=1;b.time[0]||(b.time[0]="0");break;case "2":b.word.length=b.area.length=1;b.area[0]||(b.area[0]="0");break;
default:b.type="0",b.area.length=b.time.length=1,b.area[0]||(b.area[0]="0"),b.time[0]||(b.time[0]="0")}return f.params=b};f.time=function(){var b=a.fnsDate,c=f().time,e=[];a.each(c,function(a,c){if(c.length<=2){var f=b(PPval.dataStm),h=b(+f).date(-d[c]);(c=="0"||c=="14")&&h.monthHead();c=h.format()+"|"+f.format()}e.push(c)});return e};var g=f.timeFormat=function(b){var c=a.fnsDate,b=b.split("|");b[0]=c(b[0]).format("yyyy年mm月");b[1]=c(b[1]).format("yyyy年mm月");return b.join("-")},i=f.time_format=function(b){var c=
a.fnsDate,b=b.split("|");b[0]=c(b[0]).format("yyyy-mm-dd");b[1]=c(b[1]).format("yyyy-mm-dd");return b.join(" 至 ")};f.C32=function(b){if(c&&!b)return c;else c={};var h=a.fnsDate,b=f(),l=a.cityIDname();switch(b.type){case "0":c.tags=b.word.slice();c.c32=[e[b.time[0]]||g(b.time[0]),l.get_name(b.area[0])];c.c_32=[b.time[0],c.c32[1]];if(b.time[0]in d){var k=h(PPval.dataStm),h=h(PPval.dataStm).date(-d[b.time[0]]);if(b.time[0]=="0"||b.time[0]=="14")h=h.monthHead();c.c_32[0]=h.format()+"|"+k.format()}c.c_32[0]=
i(c.c_32[0]);for(k=c.tags.length;k--;)c.tags[k]=T.string(c.tags[k]).encodeHTML();break;case "1":c.c32=[b.word[0],e[b.time[0]]||g(b.time[0])];c.c_32=[b.word[0],b.time[0]];if(b.time[0]in d){k=h(PPval.dataStm);h=h(PPval.dataStm).date(-d[b.time[0]]);if(b.time[0]=="0"||b.time[0]=="14")h=h.monthHead();c.c_32[1]=h.format()+"|"+k.format()}c.c_32[1]=i(c.c_32[1]);c.tags=[];for(k=b.area.length;k--;)c.tags[k]=l.get_name(b.area[k])}return c};f.timeStr=e;f.timeDay=d;return a.getParams=f})(BID);
BID.fillAdvPannel=function(){var a=BID.getParams(),b=T("#adv_pannel .tabUnit"),c=b.find("ul.tabUl").eq(0).find(".tabLi");b.find(".tabConts").eq(0).find(".tabCont").each(function(){var b=T(this).find("input"),c=T(this).find(".addComp");T.array(["word","area","time"]).each(function(f,g){var i=-1;b.each(function(){if(this.name==g){i+=1;if(i>=a[g].length)return"break";this.value=a[g][i];T(BID.getPnode(this,"li.comCtl")).find(".comBorderR").css({"border-color":BID.getColor(i)});g!=="word"&&(g==="area"?
(BID.regionA.setVal(this),T(this).change()):g==="time"&&BID.selectA.setVal(this));i>0&&c.click()}})})});c.eq(+a.type).click();BID.advPannelFilled=1};
BID.getNewParams=function(){var a,b={};T("#adv_pannel .tabCont").each(function(){T(this).hasClass("dsn")||(a=T(this))});T.array(["type","time","area","word"]).each(function(c,d){var e=[];a.find("input").each(function(){if(this.name==d){var a=this.value.replace(/^\s+|\s+$/g,"");!BID.getPnode(this,".dsn")&&a&&e.push(a)}});d==="type"&&(e=e[0]);b[d]=e});return b};
BID.advSearch=function(a){var a=a||BID.getNewParams(),b=T("#adv_schfm"),c=b.find("input");if(a.word.join(",")===""&&(a.word=BID.getParams().word,a.type!="0"))a.word.length=1;T.object.each(a,function(a,b){typeof a!=="string"&&(a=a.join(","));c.each(function(){if(this.name==b)this.value=a})});T.browser.ie==6&&(a=BID.getEvt(),T(a.target).closest("a").length&&(a.stopPropagation(),a.preventDefault()));b.submit()};BID.searchNew=function(a){typeof a==="string"&&(a=[a]);var b=BID.getParams();b.word=a;BID.advSearch(b)};
BID.hotWordsClick=function(){var a=BID.getEvt(),b=T(a.target);b.hasClass("hotWord")&&(BID.searchNew(T.string(b.text()).trim()),a.preventDefault())};
(function(a){function b(a,b,c){for(var c=c||g||f,b=b||"tyufCBJKQas",c=((c||"")+b).split(""),d=b.length,e=0,b={},i=0;i<c.length;i++)if(!(c[i]in b)&&(b[c[i]]=e,++e>=d)){b[c[i]]=",";break}a=a.split("");for(c=a.length;c--;)a[c]=b[a[c]];return a.join("")}var a=a||window,c=[],d=0,e="",f="",g="";a.res2=function(a){e?f?g=a:(f=a,PPval.res2=f):e=a};a.dataInterface=function(b,d,f,g){var g=g||{},n="get";PPval.status==301?a.vVerify():(!d||typeof d=="string"?(d=d||"",d.charAt(0)=="&"&&(d=d.slice(1)),g.noCache&&
(d+="&"+ +new Date)):n="post",g.loading&&a.toLoading(g.loading),b={name:b,type:n,data:d,funCbk:f,deta:{status:-1,message:"data Error",data:null,sErr:"data Err"},opts:g},e?(c.push(b),i()):j(b))};var i=function(){clearTimeout(d);c.length&&(d=setTimeout(i,20),f&&j(c.shift()))},j=function(c){var d=PPval.dataface+c.name+"?res="+PPval.ppt+(f?"&res2="+f:""),e=function(b,d){c.opts.loading&&a.toLoading(c.opts.loading,1);c.funCbk&&c.funCbk(a.sCopy({rawData:d},c.deta))},g=function(d){try{d=T.json.parse(d)}catch(e){d=
a.sCopy({rawData:d},c.deta)}if(!d.status||d.status=="0")d.status=0;else{d.status=+d.status;if(isNaN(d.status))d.status=-1;d.sErr=d.message||"data Error"}c.opts.loading&&a.toLoading(c.opts.loading,1);if(c.name in{"Search/getAllIndex/":1,"Search/getSubIndex/":1}&&f){try{for(var g=d.data.all.length;g--;)for(var i in{all:1,pc:1,wise:1}){var j=d.data[i][g],l=j.userIndexes_100;l&&(j.userIndexes_100=b(l));(l=j.userIndexes_30)&&(j.userIndexes_30=b(l))}}catch(k){}try{var m=d.data.forecast;if(m)for(var r in m){var q=
m[r];if(q)for(i in{all:1,pc:1,wise:1})if(j=q[i])(l=j.str_day_100)&&(j.str_day_100=b(l)),(l=j.str_week_100)&&(j.str_week_100=b(l))}}catch(s){}}c.funCbk&&c.funCbk(d)};if(!c.opts.noCache&&c.type!="post")return c.data&&(d+="&"+c.data),a.cjax(d,g,{error:e,async:c.opts.async});T.ajax(d,{async:c.opts.async===!1?!1:!0,type:c.type,data:c.data,timeout:2E4,error:e,success:g})}})(BID);
BID.dataBanner=function(a,b,c){a="loc="+a;b&&b.charAt(0)!="&"&&(b="&"+b);a+=b||"";BID.dataInterface("Banner/getBannerPic/",a,function(a){var a=a.data||[],b="",f=[];a.sort(function(a,b){return a.order-b.order});BID.each(a,function(a,c){b='<img class="carousel_item_img" src="'+c.image_url+'" />';c.image_href&&c.image_href!="#"?f.push({content:'<a target="_blank" class="carousel_item_href" href="'+c.image_href+'">'+b+"</a>"}):f.push({content:b})});c&&c(a,f)})};
BID.crCarousel=function(a,b,c){var d=BID.gsid(a),c=BID.sCopy(c||{},{isLoop:!0,viewSize:1,focusRange:{min:0,max:1},button:{enable:!0},autoScroll:{interval:9E3},fx:{duration:1E3}});c.button.enable=b.length>1?!0:!1;c.items=b;b=new magic.Carousel(c);b.render(d);b.on("onmouseenter",function(){this.stop()});b.on("onmouseleave",function(){this.start()});BID.crCarousel.inis[d]=b;T(a).mouseenter(function(){var a=BID.crCarousel.inis[this.id];T(a.getElement("next")).show();T(a.getElement("prev")).show()}).mouseleave(function(){var a=
BID.crCarousel.inis[this.id];T(a.getElement("next")).hide();T(a.getElement("prev")).hide()}).mouseleave()};BID.crCarousel.inis={};
BID.toLoading=function(a){var b={};return function(c,d){typeof c=="string"&&(c=T("#"+c)[0]);if(c){var e=a.gsid(c),f=T(c),g="",i=0,j=f.children(".toLoading"),c=f[0];clearTimeout(b[e]);d>0?(j.hide(),c.style.height=g):(g=c.style.height,i=f.height(),b[e]=setTimeout(function(){var a=f.children(".toLoading");if(!g&&i<90)c.style.height="90px";a.length||(a=T('<div class="toLoading"><div class="loadingImg"></div></div>'),f.prepend(a));a.show()},d<0?1:350))}}}(BID);
BID.toStamp=function(a,b,c,d){b=b||"50%";c=c||"50%";BID.gsid(a);var a=T(a),e=a.children(".toStamp");d?e.hide():(e.length||(e=T('<div class="toStamp"></div>'),a.prepend(e)),e.css({left:b,top:c}).show())};
function searchDemoWords(){var a=BID.getEvt(),b=a.target;b.tagName=="A"&&T(b).hasClass("item")?(T("#schword").val(T(b).text()).focus().closest("form").submit(),T.browser.ie==6&&(a.stopPropagation(),a.preventDefault())):b.tagName=="INPUT"&&b.type=="submit"&&(T.string(T("#schword").val()).trim()||T("#schword").val(T("#demoWords_toe a.item").eq(0).text()).focus())};(function(a){var a=a||window,b,c,d={trendKey:"搜索##{words}#的热点趋势 ——分享自@百度指数。",cMap:"搜索##{words}#的地域分布 ——分享自@百度指数。"};a.shareBlockImg=function(j,h){h=h||{};h.tpl=h.tpl||j.tpl;var l=(a.getEvt("i")||{}).target;if(l){l=T(l);if(!b)b=a.getDialog("shareDialog",{width:300,height:231})._setContent("bdsBlockImg"),b.on("hide",f),window.iiDialog=b;if(c)alert("截图处理中，请勿频繁操作");else{c={params:j,opts:h};var k=e(!0);l.hasClass("down")?(c.type="down",b.setTitleText("下载"),k.bds.hide()):(c.type="share",b.setTitleText("分享"),
c.bdsText=T.string(d[h.tpl]).format({words:a.getParams().word.join(",")}),k.bbx.attr("data",bdShare._getStrData({text:c.bdsText})));b.show();b.center();c.taskID=a.shareDown(j,{onLoad:i,onErr:g,url:h.url||"UserShare/getUserShare/"})}}};var e=function(a){var b=T("#bdsBlockImg"),c={rot:b};c.bds=b.find(".bdshareBds").show();c.bbx=b.find(".bdshareBox");c.pvu=b.find(".bdsPreview").addClass("loading_bg2").show();a&&(c.bbx.attr("data",""),c.pvu.html('<p class="infLabel">截图处理中</p>'));return c},f=function(){a.shareDown.abort(c.taskID);
c=0},g=function(a){if(c){var d=e();c.type==="share"?(a=d.pvu.removeClass("loading_bg2").html('<p class="infLabel">'+a+"</p>").height(),b.setSize({height:Math.max(231,a+85)}),b.center()):(d.bds.hide(),alert("下载失败"),b.hide(),c=0)}},i=function(a){if(c){var d=e();d.pvu.removeClass("loading_bg2");if(c.type==="share")d.pvu.html('<img class="prvImg" src="'+a+'" />').height(),d.bbx.attr("data",bdShare._getStrData({pic:a,text:c.bdsText}));else{var f=c.params;f.download=!0;f=PPval.dataface+"UserShare/getUserShare/?res="+
PPval.ppt+"&"+T.url.jsonToQuery(f);T("#bdsDownLoad").attr("action",f).submit();d.bds.hide();d.pvu.html('<img class="prvImg" src="'+a+'" /><br />如果您的浏览器没有自动开始下载<br />请在上图点击<span style="color:#e00;">右键</span>，选择<span style="font-weight:bold;">图片另存为</span>').height()}b.center()}}})(BID);
(function(a){var a=a||window,b={busy:"截图处理中",xsrc:"截图生成失败",xpic:"截图打开失败"},c,d,e,f=0,g=function(){},i=a.shareDown=function(a,e){if(c)e.onErr&&e.onErr(b.busy);else if(c=a||{},d=e||{},d.pic)j(d.pic);else return f+=1,m(d.url,T.url.jsonToQuery(c)),f},j=function(a,b){l(a,"onLoad")(k(b))},h=function(a){l(a,"onErr")(b.xsrc)},l=i.abort=function(b,h){if(b!=f)return g;e&&(a.tryaImg.abort(e),e=0);if(!c)return g;h&&(h=d[h]||g);c=d=e=0;return h},k=i.dealURI=function(a){if(a.indexOf("://")>0)return a;var b=a.slice(0,
2),c=location.href.split("/").slice(0,-1).join("/")+"/";switch(b){case "//":return a;case "..":return c+a;case "./":return c+a.slice(2)}b=location.href.split("://");return a.charAt(0)=="/"?b[0]+"://"+b[1].split("/")[0]+a:c+a},m=function(c,d){var g=f;c+=c.indexOf("?")<0?"?":"&";n(c+d,function(c){c.src?j(g,c.src):c.img?(e&&a.tryaImg.abort(e),e=a.tryaImg(k(c.img),function(a){j(g,a)},function(){h(g,b.xpic)})):h(g,b.xsrc)},function(){h(g,b.xsrc)})},n=function(b,c,d){b=b.split("?");a.dataInterface(b[0],
b.slice(1).join("?"),function(a){!a.status&&a.data?c(a.data):d(a.sErr)},{noCache:!0})}})(BID);
(function(a){var b=0,c=0,d=0,e="",f={},g=0,i=0,j=0;((a||window).tryaImg=function(a,b,c){var d=++g;f["i"+d]={taskID:d,src:a,onLoad:b,onErr:c};if(!e)e="tryaImg_theTRYimg",a=new Image,a.id=e,a.onabort=k,a.onerror=k,a.onload=m,a.style.cssText="position:absolute;left:-32767px;top:0;",document.body.appendChild(a);h();return d}).abort=function(a){a!=i?delete f["i"+a]:(j=d=0,clearTimeout(b))};var h=function(){if(j)setTimeout(h,2E3);else{for(var a;!a&&i<g;)i+=1,a=f["i"+i];(j=a)?l():document.getElementById(e).src=
"about:blank"}},l=function(){if(j){var a=j.src,b=(a.indexOf("?")<0?"?":"&")+ +new Date;document.getElementById(e).src=a+b;clearTimeout(c);c=setTimeout(k,5E3)}},k=function(){clearTimeout(b);if(++d<6&&j)b=setTimeout(l,2E3);else{try{j.onErr("加载图片失败")}catch(a){}j=d=0}},m=function(){try{j.onLoad(j.src)}catch(a){}j=d=0}})(BID);
(function(a){var a=a||window,b={};a.getDialog=function(a,e){var a=a||"dialog_comm",e=e||{},f=b[a];f?f.contentEID&&(f.contentPID?T("#"+f.contentPID):T(document.body)).append(T("#"+f.contentEID)):(f=b[a]=new magic.Dialog({draggable:!0,content:"",contentType:"html",mask:{enable:!0},buttons:{enable:!1}}),f.render());f.setTitleText(e.title||"");f.setContent(e.content||"","html");f.show();(e.width||e.height)&&f.setSize(e);f.center();f._setContent=c;return f};var c=function(b,c){this.contentEID&&(this.contentPID?
T("#"+this.contentPID):T(document.body)).append(T("#"+this.contentEID));if(c=="html")return this.contentPID=this.contentEID="",this.setContent(b,c),this;var f=T("#"+b)[0];this.contentEID=b;this.contentPID=a.gsid(f.parentNode);this.setContent(f,"element");return this}})(BID);(function(a){var b=typeof module==="undefined"?a.baidu=a.baidu||{}:module.exports;b.template=function(b,e){var f=function(){if(!a.document)return c._compile(b);var e=document.getElementById(b);if(e){if(c.cache[b])return c.cache[b];e=/^(textarea|input)$/i.test(e.nodeName)?e.value:e.innerHTML;return c._compile(e)}else return c._compile(b)}(),g=c._isObject(e)?f(e):f,f=null;return g};var c=b.template;c.versions=c.versions||[];c.versions.push("1.0.6");c.cache={};c.LEFT_DELIMITER=c.LEFT_DELIMITER||"<%";
c.RIGHT_DELIMITER=c.RIGHT_DELIMITER||"%>";c.ESCAPE=!0;c._encodeHTML=function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\\/g,"&#92;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};c._encodeReg=function(a){return String(a).replace(/([.*+?^=!:${}()|[\]/\\])/g,"\\$1")};c._encodeEventHTML=function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/\\\\/g,"\\").replace(/\\\//g,
"/").replace(/\\n/g,"\n").replace(/\\r/g,"\r")};c._compile=function(a){a="var _template_fun_array=[];\nvar fn=(function(__data__){\nvar _template_varName='';\nfor(name in __data__){\n_template_varName+=('var '+name+'=__data__[\"'+name+'\"];');\n};\neval(_template_varName);\n_template_fun_array.push('"+c._analysisStr(a)+"');\n_template_varName=null;\n})(_template_object);\nfn = null;\nreturn _template_fun_array.join('');\n";return new Function("_template_object",a)};c._isObject=function(a){return"function"===
typeof a||!!(a&&"object"===typeof a)};c._analysisStr=function(a){var b=c.LEFT_DELIMITER,f=c.RIGHT_DELIMITER,g=c._encodeReg(b),i=c._encodeReg(f),a=String(a).replace(RegExp("("+g+"[^"+i+"]*)//.*\n","g"),"$1").replace(RegExp("<\!--.*?--\>","g"),"").replace(RegExp(g+"\\*.*?\\*"+i,"g"),"").replace(RegExp("[\\r\\t\\n]","g"),"").replace(RegExp(g+"(?:(?!"+i+")[\\s\\S])*"+i+"|((?:(?!"+g+")[\\s\\S])+)","g"),function(a,b){var c="";if(b)for(c=b.replace(/\\/g,"&#92;").replace(/'/g,"&#39;");/<[^<]*?&#39;[^<]*?>/g.test(c);)c=
c.replace(/(<[^<]*?)&#39;([^<]*?>)/g,"$1\r$2");else c=a;return c}),a=a.replace(RegExp("("+g+"[\\s]*?var[\\s]*?.*?[\\s]*?[^;])[\\s]*?"+i,"g"),"$1;"+f).replace(RegExp("("+g+":?[hvu]?[\\s]*?=[\\s]*?[^;|"+i+"]*?);[\\s]*?"+i,"g"),"$1"+f).split(b).join("\t"),a=c.ESCAPE?a.replace(RegExp("\\t=(.*?)"+i,"g"),"',typeof($1) === 'undefined'?'':baidu.template._encodeHTML($1),'"):a.replace(RegExp("\\t=(.*?)"+i,"g"),"',typeof($1) === 'undefined'?'':$1,'");return a=a.replace(RegExp("\\t:h=(.*?)"+i,"g"),"',typeof($1) === 'undefined'?'':baidu.template._encodeHTML($1),'").replace(RegExp("\\t(?::=|-)(.*?)"+
i,"g"),"',typeof($1)==='undefined'?'':$1,'").replace(RegExp("\\t:u=(.*?)"+i,"g"),"',typeof($1)==='undefined'?'':encodeURIComponent($1),'").replace(RegExp("\\t:v=(.*?)"+i,"g"),"',typeof($1)==='undefined'?'':baidu.template._encodeEventHTML($1),'").split("\t").join("');").split(f).join("_template_fun_array.push('").split("\r").join("\\'")}})(window);
